# Generated by Django 4.0.3 on 2022-06-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplans',
            name='date',
            field=models.DateField(),
        ),
    ]
