# Generated by Django 4.0.3 on 2022-06-11 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_serving'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Serving',
        ),
    ]
